"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Save } from "lucide-react";
import { createClient } from "../../../lib/supabase/browser";

type Member = { id: string; display_name: string };

export function NewTaskForm({ members }: { members: Member[] }) {
  const router = useRouter(); const [saving,setSaving]=useState(false); const [error,setError]=useState("");
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setError("");const form=new FormData(e.currentTarget);const {data:{user}}=await createClient().auth.getUser();if(!user){router.push("/login");return;}const {error:insertError}=await createClient().from("tasks").insert({title:String(form.get("title")||"").trim(),description:String(form.get("description")||""),owner_id:String(form.get("owner_id")||user.id),status:String(form.get("status")),priority:String(form.get("priority")),workstream:String(form.get("workstream")),due_date:form.get("due_date")||null,progress_pct:Number(form.get("progress_pct")||0),tags:String(form.get("tags")||"").split(",").map(x=>x.trim()).filter(Boolean)});if(insertError){setError(insertError.message);setSaving(false);return;}router.push("/tasks");router.refresh();}
  return <form className="card form-card" onSubmit={submit}><div className="form-grid"><div className="field full"><label>Task title *</label><input name="title" required maxLength={200} placeholder="e.g. Validate heart-rate signal at rest" /></div><div className="field full"><label>Description</label><textarea name="description" maxLength={10000} placeholder="What does done look like? Add links or acceptance criteria..." /></div><div className="field"><label>Owner</label><select name="owner_id"><option value="">Assign to me</option>{members.map(member=><option key={member.id} value={member.id}>{member.display_name}</option>)}</select></div><div className="field"><label>Status</label><select name="status"><option value="todo">To do</option><option value="in_progress">In progress</option><option value="review">Review</option></select></div><div className="field"><label>Priority</label><select name="priority"><option>medium</option><option>low</option><option>high</option><option>critical</option></select></div><div className="field"><label>Workstream</label><select name="workstream"><option>sensors</option><option>firmware</option><option>conductive_threads</option><option>integration</option><option>testing</option><option>demo</option><option>docs</option><option>other</option></select></div><div className="field"><label>Due date</label><input name="due_date" type="date" /></div><div className="field"><label>Progress %</label><input name="progress_pct" type="number" min="0" max="100" defaultValue="0" /></div><div className="field full"><label>Tags</label><input name="tags" placeholder="hardware, prototype (comma separated)" /></div></div>{error&&<p style={{color:"#d95561",fontSize:12}}>{error}</p>}<div style={{display:"flex",justifyContent:"flex-end",gap:8,marginTop:22,paddingTop:18,borderTop:"1px solid #eef1f4"}}><button type="button" className="btn" onClick={()=>router.back()}>Cancel</button><button className="btn btn-primary" disabled={saving}><Save size={14}/>{saving?"Saving...":"Save task"}</button></div></form>;
}
